"""empty message

Revision ID: 1feb332d9122
Revises: ef1ba6b965bd
Create Date: 2023-10-31 16:50:09.444273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1feb332d9122'
down_revision = 'ef1ba6b965bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('operation', sa.String(), nullable=False))
        batch_op.drop_column('process')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('process', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('operation')

    # ### end Alembic commands ###
